In [2]:
import pandas as pd
import pandera as pa
import numpy as np
from nptyping import NDArray, Shape, Int64




# Dataframe

* add new columns
    *one column
    *two or more columns
* delete columns
* change data type of columns
* map
* apply
    * on one column
    * more than one column
* concat
    *axis
        *axis = 0 (top to bottom)
        *axis = 1 (left to rigth)

* describe dataframe
    *df.info() # total index, columns, names and data type, total fill cells
    *df.describe() # mean, std, min # statistical properties | apply only numeric values
    *df.head() # first 5 rows
    *df.tail() # last 5 rows

In [8]:
total : int = 10000
s1 : NDArray[Shape[str(total)], Int64] = np.random.randint(80,100, total)
print(len(s1))
s1

10000


array([90, 98, 98, ..., 99, 93, 93])

In [20]:
total : int = 10000
s1 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(80,100, (total,5))
ss1 :pd.DataFrame = pd.DataFrame(s1, columns=["s1","s2","s3","s4","s5"])

s2 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(70,79, (total,5))
ss2 :pd.DataFrame = pd.DataFrame(s2, columns=["s1","s2","s3","s4","s5"])

s3 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(60,69, (total,5))
ss3 :pd.DataFrame = pd.DataFrame(s3, columns=["s1","s2","s3","s4","s5"])

s4 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(50,59, (total,5))
ss4 :pd.DataFrame = pd.DataFrame(s4, columns=["s1","s2","s3","s4","s5"])

s5 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(40,49, (total,5))
ss5 :pd.DataFrame = pd.DataFrame(s5, columns=["s1","s2","s3","s4","s5"])

s6 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(33,39, (total,5))
ss6 :pd.DataFrame = pd.DataFrame(s6, columns=["s1","s2","s3","s4","s5"])

s7 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(0,32, (total,5))
ss7 :pd.DataFrame = pd.DataFrame(s7, columns=["s1","s2","s3","s4","s5"])


print(len(ss1))
print(len(ss2))
print(len(ss3))
print(len(ss4))
print(len(ss5))
print(len(ss6))
print(len(ss7))

s1

10000
10000
10000
10000
10000
10000
10000


array([[89, 92, 98, 82, 93],
       [83, 99, 91, 83, 82],
       [94, 92, 86, 98, 89],
       ...,
       [92, 98, 88, 93, 80],
       [85, 98, 84, 86, 92],
       [97, 84, 85, 98, 91]])

In [21]:
ss1

s1  s2  s3  s4  s5
0     89  92  98  82  93
1     83  99  91  83  82
2     94  92  86  98  89
3     84  90  86  90  92
4     87  82  98  80  98
...   ..  ..  ..  ..  ..
9995  95  98  87  87  90
9996  81  98  83  86  99
9997  92  98  88  93  80
9998  85  98  84  86  92
9999  97  84  85  98  91

[10000 rows x 5 columns]

In [22]:
ss2

s1  s2  s3  s4  s5
0     76  70  76  74  74
1     76  75  78  76  70
2     74  72  74  76  78
3     70  75  75  75  75
4     77  77  71  73  76
...   ..  ..  ..  ..  ..
9995  78  70  72  72  76
9996  75  77  75  78  73
9997  76  75  78  73  76
9998  74  78  73  77  70
9999  77  77  71  77  73

[10000 rows x 5 columns]

In [23]:
ss3

s1  s2  s3  s4  s5
0     63  65  64  61  65
1     63  60  64  63  64
2     65  64  60  61  68
3     63  60  65  60  63
4     63  67  67  63  61
...   ..  ..  ..  ..  ..
9995  65  66  67  65  65
9996  65  64  64  65  67
9997  67  61  62  65  60
9998  66  64  68  68  67
9999  63  65  66  65  68

[10000 rows x 5 columns]

In [27]:
df : pd.DataFrame = pd.concat([ss1,ss2,ss3,ss4,ss5,ss6,ss7])

display(df.info())
print("=========")

display(df.describe())
print("=========")

display(df.head())
print("=========")

display(df.tail())
print("=========")



<class 'pandas.core.frame.DataFrame'>
Index: 70000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   s1      70000 non-null  int32
 1   s2      70000 non-null  int32
 2   s3      70000 non-null  int32
 3   s4      70000 non-null  int32
 4   s5      70000 non-null  int32
dtypes: int32(5)
memory usage: 1.9 MB


None

s1            s2            s3            s4            s5
count  70000.000000  70000.000000  70000.000000  70000.000000  70000.000000
mean      53.807843     53.809257     53.770729     53.787486     53.758271
std       23.392220     23.371685     23.428586     23.352817     23.363054
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%       37.000000     37.000000     37.000000     37.000000     37.000000
50%       54.000000     54.000000     54.000000     54.000000     54.000000
75%       72.000000     72.000000     72.000000     72.000000     72.000000
max       99.000000     99.000000     99.000000     99.000000     99.000000

s1  s2  s3  s4  s5
0  89  92  98  82  93
1  83  99  91  83  82
2  94  92  86  98  89
3  84  90  86  90  92
4  87  82  98  80  98

s1  s2  s3  s4  s5
9995   6  21  27  21   2
9996   6  10  27  28   5
9997  11  14   0  12  16
9998   3  16  30  21  24
9999   1  30  15   3  30

In [29]:
df.to_csv("student.csv", index=False)

In [31]:
df1 : pd.DataFrame = pd.read_csv("./student.csv")
df1.head()

s1  s2  s3  s4  s5
0  89  92  98  82  93
1  83  99  91  83  82
2  94  92  86  98  89
3  84  90  86  90  92
4  87  82  98  80  98

# apply operations on columns
    * Extract one column from DataFrame
        * dataframe['column']
            * add new column
            * get column with space between columns text
        * dataframe.column
            * not add new column
            * not get column with space between column text
    * Extract two or more columns from DataFrame
        * dataframe[['column1', 'column2']]
            * pass list into Dataframe


In [32]:
df.head()

s1  s2  s3  s4  s5
0  89  92  98  82  93
1  83  99  91  83  82
2  94  92  86  98  89
3  84  90  86  90  92
4  87  82  98  80  98

In [34]:
df['s5']

0        93
1        82
2        89
3        92
4        98
         ..
69995     2
69996     5
69997    16
69998    24
69999    30
Name: s5, Length: 70000, dtype: int64

In [35]:
df.s1

0        89
1        83
2        94
3        84
4        87
         ..
69995     6
69996     6
69997    11
69998     3
69999     1
Name: s1, Length: 70000, dtype: int64

In [36]:
df[["s1","s2","s3","s4","s5"]]

s1  s2  s3  s4  s5
0      89  92  98  82  93
1      83  99  91  83  82
2      94  92  86  98  89
3      84  90  86  90  92
4      87  82  98  80  98
...    ..  ..  ..  ..  ..
69995   6  21  27  21   2
69996   6  10  27  28   5
69997  11  14   0  12  16
69998   3  16  30  21  24
69999   1  30  15   3  30

[70000 rows x 5 columns]

# Add new Column
    * Addition operation on column

In [37]:
df.head()

s1  s2  s3  s4  s5
0  89  92  98  82  93
1  83  99  91  83  82
2  94  92  86  98  89
3  84  90  86  90  92
4  87  82  98  80  98

In [40]:
df['Total'] = 500 # add new column
df['Total'] = 300 # update column value
del df['Total'] # delete column
df

s1  s2  s3  s4  s5
0      89  92  98  82  93
1      83  99  91  83  82
2      94  92  86  98  89
3      84  90  86  90  92
4      87  82  98  80  98
...    ..  ..  ..  ..  ..
69995   6  21  27  21   2
69996   6  10  27  28   5
69997  11  14   0  12  16
69998   3  16  30  21  24
69999   1  30  15   3  30

[70000 rows x 5 columns]

In [44]:
df.Total = 500 # update column value
# df['Total'] = 300 # update column value
del df.Total = 300 # delete column
df

SyntaxError: invalid syntax (1429989744.py, line 3)

In [45]:
s1

array([[89, 92, 98, 82, 93],
       [83, 99, 91, 83, 82],
       [94, 92, 86, 98, 89],
       ...,
       [92, 98, 88, 93, 80],
       [85, 98, 84, 86, 92],
       [97, 84, 85, 98, 91]])

In [48]:
df['s1'] + df["s2"]+ df["s3"]+ df["s4"]+ df["s5"]

0        454
1        438
2        459
3        442
4        445
        ... 
69995     77
69996     76
69997     53
69998     94
69999     79
Length: 70000, dtype: int64

In [49]:
display(df.head())

s1  s2  s3  s4  s5
0  89  92  98  82  93
1  83  99  91  83  82
2  94  92  86  98  89
3  84  90  86  90  92
4  87  82  98  80  98

In [52]:
print(89+89 )
df["s1"] + df["s2"]+ df["s3"]+ df["s4"]+ df["s5"]

178


0        454
1        438
2        459
3        442
4        445
        ... 
69995     77
69996     76
69997     53
69998     94
69999     79
Length: 70000, dtype: int64

In [53]:
df["obtained"] = df["s1"] + df["s2"]+ df["s3"]+ df["s4"]+ df["s5"]
df

s1  s2  s3  s4  s5  obtained
0      89  92  98  82  93       454
1      83  99  91  83  82       438
2      94  92  86  98  89       459
3      84  90  86  90  92       442
4      87  82  98  80  98       445
...    ..  ..  ..  ..  ..       ...
69995   6  21  27  21   2        77
69996   6  10  27  28   5        76
69997  11  14   0  12  16        53
69998   3  16  30  21  24        94
69999   1  30  15   3  30        79

[70000 rows x 6 columns]

In [58]:
df["obtained"] = df["s1"] + df["s2"]+ df["s3"]+ df["s4"]+ df["s5"]
df["percentage"] = df["obtained"] / df["Total"] * 100
df

KeyError: 'Total'